/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donneeConsulter;

/**
 *
 * @author guerin
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        jLabel1.setText("Email: franckelricj23@gmail.com");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 287, 17);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        jLabel2.setText("bac + 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 70, 17);

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        jLabel4.setText("Email: armelguerin23@gmail.com");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 292, 17);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 0, 0, 0);

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        jLabel7.setText("copyright®By Guerin Njike");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 120, 240, 17);

        jLabel8.setFont(new java.awt.Font("Bodoni MT Black", 3, 14)); // NOI18N
        jLabel8.setText("2019");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 120, 50, 17);

        setSize(new java.awt.Dimension(322, 204));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
