/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donneeConsulter;

import donnee.base_de_donnee;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import traitement.interfaceDirecteur;

/**
 *
 * @author guerin
 */
public class consulteFacture extends javax.swing.JFrame {
    

    /**
     * Creates new form consulteFacture
     */
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    DefaultTableModel Model = new DefaultTableModel();
    
    public consulteFacture() {
        initComponents();
        Model.addColumn("Chambre");
        Model.addColumn("client");
        Model.addColumn("date de facture");
        Model.addColumn("type de paiement");
        Model.addColumn("montant");
        Model.addColumn("QTE");
        Model.addColumn("total_payer");
        
        
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select client.Nom , chambre.numChambre, facture.DateFacture , facture.typepaiement , facture.Montant, facture.qte, facture.mntTTC from client, chambre inner join facture where client.idclient = facture.idClient and chambre.idChambre = facture.idChambre");
            while(rs.next()){
                Model.addRow(new Object[]{ rs.getString("numChambre"),rs.getString("Nom"),rs.getString("DateFacture"),rs.getString("typepaiement"),rs.getString("Montant"), rs.getString("qte"), rs.getString("mntTTC")});
               
            }
            
        }catch(SQLException e){System.err.println(e);}
        facture.setModel(Model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facture = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("liste des factures effectuees");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donneeConsulter/go-back256_24856.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 70, 50));

        facture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        facture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        facture.setShowHorizontalLines(true);
        facture.setShowVerticalLines(true);
        facture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                factureMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(facture);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, 230));

        jButton7.setBackground(new java.awt.Color(51, 204, 0));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("F:\\mini projet java avec swing\\projet_de_stage\\src\\donneeConsulter\\Print_icon-icons.com_73705.png")); // NOI18N
        jButton7.setText("imprimer");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**private void facturefill(){
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select facture.idFacture , chambre.numChambre, facture.DateFacture , facture.typepaiement , facture.Montant from chambre inner join facture where chambre.idChambre = facture.idChambre");
            facture.setModel(Model);
            while(rs.next()){
            Model.addElement("Facture N : "+ rs.getInt(1)+ "   Designation= " + rs.getString(2)+ "   Date_facture : " + rs.getString(3)+ "   type_paiement : "+ rs.getString(4)+ "         ,Montant : "+ rs.getInt(5)+ "   ");
            
            }
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }*/
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        interfaceDirecteur iD = new interfaceDirecteur();
        iD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void factureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_factureMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_factureMouseClicked
    private void imprimer(){
          MessageFormat en_tete = new MessageFormat(" Listes des Factures  ");
         MessageFormat pied = new MessageFormat("Page (0, nombre, integer)");
         try{
         facture.print(JTable.PrintMode.NORMAL, en_tete, pied);
         }
         catch(java.awt.print.PrinterException e){
         System.err.format("impossible d'imprimer %s%n", e.getMessage());
         }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        imprimer();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulteFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulteFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulteFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulteFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulteFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable facture;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
