/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donneeConsulter;

/**
 *
 * @author guerin
 */


import donnee.base_de_donnee;
import java.awt.HeadlessException;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import traitement.Connexion;
import traitement.interfaceReceptionniste;


public class consulterReservation extends javax.swing.JFrame {

    /**
     * Creates new form consulterReservation
     */
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    DefaultTableModel Model = new DefaultTableModel();
    
    
    public consulterReservation() {
        initComponents();
        Model.addColumn("client");
        Model.addColumn("chambre");
        Model.addColumn("date_reservation");
        Model.addColumn("date_arrivee");
        Model.addColumn("date_depart");
        Model.addColumn("nbre_Jours");
        Model.addColumn("id");
        
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery(" SELECT client.Nom , chambre.numChambre , reservation.dateReservation, reservation.dateArrive, reservation.dateDepart, reservation.nbrJour,reservation.idReservation FROM client, chambre, reservation "
                    + "WHERE client.idClient = reservation.idClient and chambre.idChambre = reservation.idChambre ");
            while(rs.next()){
               Model.addRow( new Object[] { rs.getString("Nom"), rs.getInt("numChambre"), rs.getString("dateReservation"), rs.getString("dateArrive"),
                   rs.getString("dateDepart"), rs.getInt("nbrJour"),rs.getInt("idReservation")
               });
            }
        
    }catch (SQLException e){System.err.println(e);}
        list.setModel(Model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nbrepersonne = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        datereservation = new javax.swing.JTextField();
        chambre = new javax.swing.JTextField();
        datearrive = new javax.swing.JTextField();
        datedepart = new javax.swing.JTextField();
        client = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("liste de reservation");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\guerin\\Downloads\\Cancel_icon-icons.com_73703.png")); // NOI18N
        jButton2.setText("supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, -1, 50));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\guerin\\Downloads\\editnote_pencil_edi_6175.png")); // NOI18N
        jButton1.setText("modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 200, 50));
        getContentPane().add(nbrepersonne, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 90, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("nombre de jour(s)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 130, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("date de depart");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 130, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("date d'arrivee");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 266, 100, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("date de reservation");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 206, 140, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("chambre");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 146, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 3, 24)); // NOI18N
        jLabel9.setText("listes des reservations effecutées");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\guerin\\Downloads\\blue_update_arrow_right_12427.png")); // NOI18N
        jButton3.setText("actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, 50));

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        list.setShowHorizontalLines(true);
        list.setShowVerticalLines(true);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 513, -1));
        getContentPane().add(datereservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 150, 30));
        getContentPane().add(chambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 150, 30));

        datearrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datearriveActionPerformed(evt);
            }
        });
        getContentPane().add(datearrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 288, 150, 30));
        getContentPane().add(datedepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 150, 30));
        getContentPane().add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 150, 30));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setText("retour");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("client");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deplace(int i){
        
        try{
    client.setText(Model.getValueAt(i,0).toString());
    chambre.setText(Model.getValueAt(i,1).toString());
    datereservation.setText(Model.getValueAt(i,2).toString());
    datearrive.setText(Model.getValueAt(i,3).toString());
    datedepart.setText(Model.getValueAt(i,4).toString());
    nbrepersonne.setText(Model.getValueAt(i,5).toString());
    }catch(Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur dans le code "+e.getLocalizedMessage());}
        }
void actualiser(){
    try{
             Model.setRowCount(0);
            st = connex.getconnexion().createStatement();
           rs = st.executeQuery(" SELECT client.Nom , chambre.numChambre , reservation.dateReservation, reservation.dateArrive, reservation.dateDepart, reservation.nbrJour,reservation.idReservation FROM client, chambre, reservation "
                    + "WHERE client.idClient = reservation.idClient and chambre.idChambre = reservation.idChambre ");
            while(rs.next()){
               Model.addRow( new Object[] { rs.getString("Nom"), rs.getInt("numChambre"), rs.getString("dateReservation"), rs.getString("dateArrive"),
                   rs.getString("dateDepart"), rs.getInt("nbrJour"),rs.getInt("idReservation")
               });
            }
            
        }catch(SQLException e){System.err.println(e);}
        list.setModel(Model);
        client.setText("");
        chambre.setText("");
        datereservation.setText("");
        datearrive.setText("");
        datedepart.setText("");
        nbrepersonne.setText("");
        
    }
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int ligne = list.getSelectedRow();
            String cible = list.getModel().getValueAt(ligne, 6).toString();
        try{
            if(JOptionPane.showConfirmDialog(null, "vous allez supprimer une reservation , voulez vous continuer ?","reservation supprimer avec success",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            if( cible.length() != 0){
                st.executeUpdate("delete from reservation where idReservation="+cible);
            }else{JOptionPane.showMessageDialog(null, "veuillez remplir la date de reservation svp!");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de suppression "+e.getMessage());}

        actualiser();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int ligne = list.getSelectedRow();
            String cible = list.getModel().getValueAt(ligne, 6).toString();
        try{
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification", "modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION){
                st.executeUpdate("update reservation set dateReservation='"+datereservation.getText()+"',dateArrive='"+datearrive.getText()+"', dateDepart='"+datedepart.getText()+"', nbrJour='"+nbrepersonne.getText()+"' where idReservation="+cible);
            }

        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de modification  ");System.err.println(e);}

        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      actualiser();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
       try{
            int i;
            i =  list.getSelectedRow();
            deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de fonctionnalite"+e.getLocalizedMessage());}
    
    }//GEN-LAST:event_listMouseClicked

    private void datearriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datearriveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datearriveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        interfaceReceptionniste iR = new interfaceReceptionniste();
        iR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulterReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulterReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulterReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulterReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulterReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chambre;
    private javax.swing.JTextField client;
    private javax.swing.JTextField datearrive;
    private javax.swing.JTextField datedepart;
    private javax.swing.JTextField datereservation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable list;
    private javax.swing.JTextField nbrepersonne;
    // End of variables declaration//GEN-END:variables
}
