/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donneeConsulter;

import donnee.base_de_donnee;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import traitement.Connexion;

/**
 *
 * @author guerin
 */
public class userManager extends javax.swing.JFrame {

    /**
     * Creates new form userManager
     */
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    DefaultTableModel Model = new DefaultTableModel();
    public userManager() {
        initComponents();
        Model.addColumn("Id_user");
        Model.addColumn("login");
        Model.addColumn("password");
        Model.addColumn("fonction");
        
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select * from utilisateur");
            while(rs.next()){
                Model.addRow(new Object[]{rs.getString("idUtilisateur"),rs.getString("Login"), rs.getString("Password"), rs.getString("Role")});
               
            }
            
        }catch(SQLException e){System.err.println(e);}
        tableUser.setModel(Model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rol = new javax.swing.JTextField();
        log = new javax.swing.JTextField();
        mdp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des utilisateurs");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(370, 40, 250, 406);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestion des utilisateurs");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 10, 270, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, -6, 0, 40);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("role :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 100, 50, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel2.setText("login :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 50, 19);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("liste des utilisateurs en service");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 340, 30);
        jPanel1.add(rol);
        rol.setBounds(120, 100, 150, 30);
        jPanel1.add(log);
        log.setBounds(120, 20, 150, 30);
        jPanel1.add(mdp);
        mdp.setBounds(120, 60, 150, 30);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUser.setShowHorizontalLines(true);
        tableUser.setShowVerticalLines(true);
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUser);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 180, 340, 140);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donneeConsulter/blue_update_arrow_right_12427.png"))); // NOI18N
        jButton1.setText("modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 90, 150, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donneeConsulter/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        jButton2.setText("ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 30, 150, 40);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donneeConsulter/icons8-poubelle-40.png"))); // NOI18N
        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 150, 150, 40);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel6.setText("mot de passe :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 60, 100, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void deplace(int i){
        try{
    log.setText(Model.getValueAt(i,1).toString());
    mdp.setText(Model.getValueAt(i,2).toString());
    rol.setText(Model.getValueAt(i,3).toString());
    }catch(Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de modification"+e.getLocalizedMessage());}
        }
    void actualiser(){
    try{
             Model.setRowCount(0);
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select * from utilisateur");
            while(rs.next()){
                Model.addRow(new Object[]{rs.getString("idUtilisateur"),rs.getString("Login"), rs.getString("Password"), rs.getString("Role")});
               
            }
            
        }catch(SQLException e){System.err.println(e);}
            log.setText("");
            mdp.setText("");
            rol.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            int ligne = tableUser.getSelectedRow();
            String id = tableUser.getModel().getValueAt(ligne, 0).toString();
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification", "modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION){
                st.executeUpdate("update utilisateur set Login='"+log.getText()+"',Password='"+mdp.getText()+"',Role='"+rol.getText()+"'where idUtilisateur="+id);
            }

        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de modification");System.err.println(e);}

        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String requete = "INSERT INTO utilisateur (Login, Password, Role) values ('"+log.getText()+"','"+mdp.getText()+"','"+rol.getText()+"')";
        try {
            st = connex.getconnexion().createStatement();
            st.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "effectuer");
            
        }catch (SQLException ex){
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualiser();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            int ligne = tableUser.getSelectedRow();
            String id = tableUser.getModel().getValueAt(ligne, 0).toString();
            if(JOptionPane.showConfirmDialog(null, "vous allez supprimer un utilisateur, voulez vous continuer ?","Effectuer",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            if(id.length() != 0){
                st.executeUpdate("delete from utilisateur where idUtilisateur="+id);
            }else{JOptionPane.showMessageDialog(null, "ERREUR");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de suppression"+e.getMessage());}

        actualiser();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        int i;
        i = tableUser.getSelectedRow();
        deplace(i);
    }//GEN-LAST:event_tableUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField log;
    private javax.swing.JTextField mdp;
    private javax.swing.JTextField rol;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
