/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sous_traitement;

import donnee.base_de_donnee;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import traitement.Connexion;
import traitement.interfaceChef;
import traitement.interfaceReceptionniste;

/**
 *
 * @author guerin
 */
public class GestionClients extends javax.swing.JFrame {

    /**
     * Creates new form GestionClients
     */
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    DefaultTableModel Model = new DefaultTableModel();
    public GestionClients() {
        initComponents();
        Model.addColumn("nom");
        Model.addColumn("prenom");
        Model.addColumn("telephone");
        Model.addColumn("profession");
        Model.addColumn("nationalite");
        Model.addColumn("adresse");
        Model.addColumn("type_de_Piece");
        Model.addColumn("passport_cni");
        
        
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select Nom , prenom, telephone, profession, adresse, nationalite, typeDePiece, passport_cni from client");
            while(rs.next()){
                Model.addRow(new Object[]{ rs.getString("nom"),rs.getString("prenom"),rs.getString("telephone"),rs.getString("profession"),rs.getString("adresse"),rs.getString("nationalite"),
                rs.getString("typeDePiece"),rs.getString("passport_cni")});
               
            }
            
        }catch(SQLException e){System.err.println(e);}
        client.setModel(Model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nat = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        adr = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        client = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        prof = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datd = new javax.swing.JLabel();
        rech = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("interface receptionniste Gestion des Clients bienvenue a l'hotel le printemps");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/find_search_card_user_16713.png"))); // NOI18N
        jButton1.setText("rechercher un client");
        jButton1.setContentAreaFilled(false);
        jButton1.setHideActionText(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, 70));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel3.setText("nationalite");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel4.setText("Liste des clients enregister");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel5.setText("prenom");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel6.setText("adresse");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/go-back256_24856.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 70, 60));
        jPanel1.add(nat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, -1));
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, -1));
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, -1));
        jPanel1.add(adr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Generate-tables_37132.png"))); // NOI18N
        jButton3.setText("modifier");
        jButton3.setContentAreaFilled(false);
        jButton3.setHideActionText(true);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 70));

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.setContentAreaFilled(false);
        jButton4.setEnabled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 110, 70));

        client.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        client.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        client.setForeground(new java.awt.Color(0, 0, 0));
        client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        client.setShowHorizontalLines(true);
        client.setShowVerticalLines(true);
        client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(client);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 590, 190));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel7.setText("telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));
        jPanel1.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));
        jPanel1.add(prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel11.setText("profession");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel14.setText("passeport ou cni");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, -1));

        datd.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        datd.setForeground(new java.awt.Color(0, 51, 51));
        datd.setText("entrer le nom du client ");
        jPanel1.add(datd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
        jPanel1.add(rech, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 220, 30));

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Save_37110.png"))); // NOI18N
        jButton5.setText("enregistrer");
        jButton5.setContentAreaFilled(false);
        jButton5.setHideActionText(true);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 120, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/LOGO PRINTEMP.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 140, 150));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel15.setText("type de piece");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNI", "PassePort" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 266, 150, 30));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 3, 15)); // NOI18N
        jLabel9.setText("nom");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jButton6.setText("actualiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jButton7.setBackground(new java.awt.Color(51, 204, 0));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Print_icon-icons.com_73705.png"))); // NOI18N
        jButton7.setText("imprimer");
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 100, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void deplace(int i){
        try{
    nom.setText(Model.getValueAt(i,0).toString());
    prenom.setText(Model.getValueAt(i,1).toString());
    tel.setText(Model.getValueAt(i,2).toString());
    prof.setText(Model.getValueAt(i,3).toString());
    nat.setText(Model.getValueAt(i,4).toString());
    adr.setText(Model.getValueAt(i,5).toString());
    type.setSelectedItem(Model.getValueAt(i,6).toString());
    pass.setText(Model.getValueAt(i,7).toString());
    
   
    }catch(Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur dans le code"+e.getLocalizedMessage());}
        }

void actualiser(){
    try{
            Model.setRowCount(0);
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select Nom , prenom, telephone, profession, adresse, nationalite, typeDePiece, passport_cni from client");
            while(rs.next()){
                Model.addRow(new Object[]{ rs.getString("nom"),rs.getString("prenom"),rs.getString("telephone"),rs.getString("profession"),rs.getString("adresse"),rs.getString("nationalite"),
                rs.getString("typeDePiece"),rs.getString("passport_cni")});
            }
            
        }catch(SQLException e){System.err.println(e);}
        client.setModel(Model);
        nom.setText("");
        prenom.setText("");
        nat.setText("");
        adr.setText("");
        tel.setText("");
        prof.setText("");
        type.setSelectedItem("");  
        rech.setText("");
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Model.setRowCount(0);
            {
                rs= st.executeQuery("select Nom , prenom, nationalite, adresse, telephone, profession, passport_cni , typeDePiece from client where Nom='"+rech.getText()+"' ");
            }while(rs.next()){
            Object[] client ={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
            Model.addRow(client);
            }if(Model.getRowCount()==0){JOptionPane.showMessageDialog(null, "client non trouver");
            }else{
            int i =0;
            deplace(i);
            }
           
        }catch(HeadlessException | SQLException e){System.err.println(e);
        JOptionPane.showMessageDialog(null,e.getMessage());
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         interfaceReceptionniste iR = new interfaceReceptionniste();
        iR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification", "modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION){
                st.executeUpdate("update client set Nom='"+nom.getText()+"',Prenom='"+prenom.getText()+"',nationalite='"+nat.getText()+"',adresse='"+adr.getText()+"'"
                        + " ,telephone='"+tel.getText()+"' "
                        + " ,typeDePiece='"+type.getSelectedItem().toString()+"',passport_cni='"+pass.getText()+"' where passport_cni='"+pass.getText()+"'");
            }

        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de modification");System.err.println(e);}

        actualiser();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            if(JOptionPane.showConfirmDialog(null, "vous allez supprimer un client de la base de donnee , voulez vous continuer ?","client supprimer avec success",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            if(nom.getText().length() != 0){
                st.executeUpdate("delete from client where passport_cni="+pass.getText());
            }else{JOptionPane.showMessageDialog(null, "veuillez remplir les infos du client svp!");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de suppression"+e.getMessage());}

        actualiser();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMouseClicked
        // TODO add your handling code here:
        try{
            int i;
            i =  client.getSelectedRow();
            deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de fonctionnalite"+e.getLocalizedMessage());}
    }//GEN-LAST:event_clientMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String requete = "insert into client (Nom , prenom, nationalite, adresse, telephone, typeDePiece, passport_cni, profession ) values ('"+nom.getText()+"','"+prenom.getText()+"','"+nat.getText()+"','"+adr.getText()+"','"+tel.getText()+"','"+type.getSelectedItem().toString()+"','"+pass.getText()+"','"+prof.getText()+"')";
       
      
        try {
        st = connex.getconnexion().createStatement();
        st.executeUpdate(requete);
        JOptionPane.showMessageDialog(null, "enregistrement effectuer avec success");
       
        
        }catch (SQLException ex){
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        
        
    } 
        actualiser(); 
    }//GEN-LAST:event_jButton5ActionPerformed
    
     private void imprimer(){
          MessageFormat en_tete = new MessageFormat(" Listes des Clients  ");
         MessageFormat pied = new MessageFormat("Page (0, nombre, integer)");
         try{
         client.print(JTable.PrintMode.NORMAL, en_tete, pied);
         }
         catch(java.awt.print.PrinterException e){
         System.err.format("impossible d'imprimer %s%n", e.getMessage());
         }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        actualiser();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       imprimer();
       actualiser();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionClients().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTable client;
    private javax.swing.JLabel datd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nat;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prof;
    private javax.swing.JTextField rech;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
