/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sous_traitement;

import donnee.base_de_donnee;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import traitement.Connexion;
import traitement.interfaceChef;

/**
 *
 * @author guerin
 */
public class GestionTarifs extends javax.swing.JFrame {

    /**
     * Creates new form GestionTarifs
     */
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    DefaultTableModel Model = new DefaultTableModel();
    
    public GestionTarifs() {
        initComponents();
        Model.addColumn("prix");
        Model.addColumn("type");
        
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select * from tarif");
            while(rs.next()){
                Model.addRow(new Object[]{rs.getString("prix"),rs.getString("type")});
               
            }
            
        }catch(SQLException e){System.err.println(e);}
        tarif.setModel(Model);
    }
    private void deplace(int i){
        try{
    p.setText(Model.getValueAt(i,0).toString());
    t.setText(Model.getValueAt(i,1).toString());
    }catch(Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de modification"+e.getLocalizedMessage());}
        }
    void actualiser(){
    try{
             Model.setRowCount(0);
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select * from tarif");
            while(rs.next()){
                Model.addRow(new Object[]{rs.getString("prix"),rs.getString("type")});
                
            }
            
        }catch(Exception e){System.err.println(e);}
        tarif.setModel(Model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarif = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("interface du Chef de reception Gestion des tarifs bienvenue");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Liste des tarifs disnopibles");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 400, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/go-back256_24856.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 60, 50));

        t.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, -1));

        p.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, -1));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/blue_update_arrow_right_12427.png"))); // NOI18N
        jButton3.setText("mettre a jour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Cancel_icon-icons.com_73703.png"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 180, 60));

        tarif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        tarif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tarif.setShowHorizontalLines(true);
        tarif.setShowVerticalLines(true);
        tarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarifMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tarif);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 420, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/LOGO PRINTEMP.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 150));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("prix");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String requete = "INSERT INTO tarif (prix, type) values ('"+p.getText()+"','"+t.getText()+"')";
        try {
            st = connex.getconnexion().createStatement();
            st.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "le nouveau tarif a ete ajouter ");
            p.setText("");
            t.setText("");
        }catch (SQLException ex){
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        interfaceChef C = new interfaceChef();
        C.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            if(JOptionPane.showConfirmDialog(null, "confirmer la modification", "modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION){
                st.executeUpdate("update tarif set prix='"+p.getText()+"',type='"+t.getText()+"'where prix='"+p.getText()+"'or type="+p.getText());
            }

        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de modification");System.err.println(e);}

        actualiser();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            if(JOptionPane.showConfirmDialog(null, "vous allez supprimer un tarif, voulez vous continuer ?","tarif supprimer avec success",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION)
            if(p.getText().length() != 0){
                st.executeUpdate("delete from tarif where prix="+p.getText());
            }else{JOptionPane.showMessageDialog(null, "veuillez remplir le prix du tarif svp!");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, "erreur de suppression"+e.getMessage());}

        actualiser();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifMouseClicked
        // TODO add your handling code here:
        try{
            int i;
            i =  tarif.getSelectedRow();
            deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null, "erreur de fonctionnalite"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tarifMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTarifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTarifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTarifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTarifs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTarifs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField p;
    private javax.swing.JTextField t;
    private javax.swing.JTable tarif;
    // End of variables declaration//GEN-END:variables
}
