/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sous_traitement;

import donnee.base_de_donnee;
import donneeConsulter.consulterReservation;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import traitement.Connexion;
import traitement.interfaceChef;
import traitement.interfaceReceptionniste;

/**
 *
 * @author guerin
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    
    base_de_donnee connex = new base_de_donnee();
    Connection db;
    ResultSet rs;
    Statement st;
    
    public Reservation() {
        initComponents();
        Fillcombo();
        Fillcombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        listchambre = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        listclient = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        idch = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nbrepersonne = new javax.swing.JTextField();
        idcli = new javax.swing.JLabel();
        datearrive = new com.toedter.calendar.JDateChooser();
        datereservation = new com.toedter.calendar.JDateChooser();
        datedepart = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        aff1 = new javax.swing.JTextField();
        aff2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("formulaire de reservation");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Save_37110.png"))); // NOI18N
        jButton1.setText("enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 200, 50));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("date d'arrivee");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("type de chambre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("date de depart");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/Analyzeloop3x_42173.png"))); // NOI18N
        jButton2.setText("consulter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, 50));

        listchambre.setBackground(new java.awt.Color(255, 255, 255));
        listchambre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        listchambre.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                listchambrePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(listchambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setText("chambre");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        listclient.setBackground(new java.awt.Color(255, 255, 255));
        listclient.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        listclient.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                listclientPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        listclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listclientActionPerformed(evt);
            }
        });
        jPanel1.add(listclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 160, 30));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel9.setText("client");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        idch.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        idch.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(idch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 20));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/go-back256_24856.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sous_traitement/LOGO PRINTEMP.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 140, 150));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setText("nombre de jour(s)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, -1));
        jPanel1.add(nbrepersonne, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 150, -1));

        idcli.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        idcli.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(idcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 60, 20));
        jPanel1.add(datearrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, -1));
        jPanel1.add(datereservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));
        jPanel1.add(datedepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 150, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("date de reservation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, -1));

        aff1.setEnabled(false);
        jPanel1.add(aff1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        aff2.setEnabled(false);
        jPanel1.add(aff2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setText("tarif ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(496, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void fillcomboclient(){
            try{
                       st = connex.getconnexion().createStatement();
                       rs = st.executeQuery("select client.idClient from client where client.nom = '"+listclient.getSelectedItem().toString()+"' ");
                       while(rs.next()){
                           if(listclient.getSelectedItem() != null){ idcli.setText(rs.getString(1));
                                idcli.setVisible(false);}
                       }
            } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }}
    private void fillcombochambre(){
            try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select idChambre, chambre.Type, tarif.Prix from tarif inner join chambre where numChambre = '"+listchambre.getSelectedItem().toString()+"' and tarif.idTarif = chambre.idTarif");
            while(rs.next()){
                idch.setText(rs.getString(1));
                aff1.setText(rs.getString(2));
                aff2.setText(rs.getString(3));
                idch.setVisible(false);
           
            }} catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }}
    
    private void Fillcombo(){
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select nom from client");
            while(rs.next()){
            listclient.addItem(rs.getString(1));
            
            }
        
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
     private void Fillcombo2(){
        try{
            st = connex.getconnexion().createStatement();
            rs = st.executeQuery("select numChambre from chambre where Etat ='libre' ");
            while(rs.next()){
            listchambre.addItem(rs.getString(1));
            
            }
        
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.sql.Date date = new java.sql.Date(datearrive.getDate().getTime());
        java.sql.Date date2 = new java.sql.Date(datereservation.getDate().getTime());
        java.sql.Date date3 = new java.sql.Date(datedepart.getDate().getTime());
        String requete = "INSERT INTO reservation (dateReservation, dateArrive, dateDepart , nbrJour, idClient, idChambre) values ('"+date2+"','"+date+"','"+date3+"','"+nbrepersonne.getText()+"' , "
                + "'"+idcli.getText()+"', '"+idch.getText()+"') ";
        try {
            st = connex.getconnexion().createStatement();
            st.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, " success ");
            nbrepersonne.setText("");
            idcli.setText("");
            idch.setText("");
            
        }catch (SQLException ex){
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        consulterReservation CR = new consulterReservation();
        CR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        interfaceReceptionniste iR = new interfaceReceptionniste();
        iR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listclientActionPerformed

    private void listclientPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_listclientPopupMenuWillBecomeInvisible
        fillcomboclient();
    }//GEN-LAST:event_listclientPopupMenuWillBecomeInvisible

    private void listchambrePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_listchambrePopupMenuWillBecomeInvisible
        fillcombochambre();
    }//GEN-LAST:event_listchambrePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aff1;
    private javax.swing.JTextField aff2;
    private com.toedter.calendar.JDateChooser datearrive;
    private com.toedter.calendar.JDateChooser datedepart;
    private com.toedter.calendar.JDateChooser datereservation;
    private javax.swing.JLabel idch;
    private javax.swing.JLabel idcli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listchambre;
    private javax.swing.JComboBox<String> listclient;
    private javax.swing.JTextField nbrepersonne;
    // End of variables declaration//GEN-END:variables
}
